app = "personalizados-backend"
primary_region = "mia"

[build]
dockerfile = "./DockerFile"

[[services]]
internal_port = 3_000
protocol = "tcp"

  [[services.ports]]
  port = 3001

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"