# fly.toml app configuration file generated for personalizados-backend-aged-silence-9093 on 2024-11-19T21:24:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personalizados-backend-aged-silence-9093'
primary_region = 'mia'

[build]
  dockerfile = './DockerFile'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
